<?php include "header.php"; ?>
<div class="container text-light mt-4">
    <h4>TERMS AND CONDITIONS</h4>
<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
<p>
  <br>
</p>
<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of www.srihits.lk website.</p>
<p>
  <br>
</p>
<p>User Agreement</p>
<p>This User Agreement contains rules and regulations, policies, terms &amp; conditions and agreement applicable to any person who may access or use CINEFILMS LANKA (PVT) LTD, including any sub domains, web pages or extension of srihits.lk.; you hereby agree and acknowledge to be bound by the terms of this User Agreement.</p>
<p>
  <br>
</p>
<p>The use of CINEFILMSLANKA (PVT) LTD and the services provided are subject to the rules and regulations, policies, notices, terms &amp; conditions set forth in this User Agreement. For the purposes of this User Agreement, ‘User’ and wherever the context may require ‘You’ (or any variation thereof), shall mean any natural or legal person who has agreed to become a user of CINEFILMSLANKA (PVT) LTD by accessing or browsing the Website and/or has registered as a member of CINEFILMSLANKA (PVT) LTD by submitting identification information/ registration details using the computer system of CINEFILMSLANKA (PVT) LTD and accepting the electronic record of the User Agreement, has obtained a unique username along and a secret alpha-numerical key (password) for using the Website.</p>
<p>
  <br>
</p>
<p>Amendment:CINEFILMSLANKA (PVT) LTD (Henceforth referred to as “Company”) reserves the right to change this Website and/or alter the terms and conditions of this User Agreement at any time and retains the right to deny access to anyone who the Company believes has violated the provisions of this User Agreement. You are advised that any amendment to the User Agreement or rules and policies incorporated herein by reference will only be notified on the Website on publicly accessible links and you agree by accessing, browsing or using this website that this constitutes sufficient notice for all purposes against you. The revised version/ terms shall be effective from the time that the Company posts the same on the Website. [In the event, that the User Agreement includes a substantial change, the Company will provide 30 days’ prior notice of such substantial change by posting the same on the Website and also at the email address provided by the User to the Company. For the purposes of this User Agreement, ‘substantial change’ means a change to the terms of this User Agreement that reduces your rights or increases your responsibilities.]</p>
<p>
  <br>
</p>
<p>Definitions</p>
<p>Payment on Billing shall mean a Transaction where the payment for the items purchased is paid through the (i) CINEFILMSLANKA (PVT) LTD authorized Payment Gateway Facility or (ii) the buyer (if permitted by the relevant seller) has opted to deposit the Transaction Price in the bank account of the Company by way of cash, cheque, demand draft or any other mode of payment and such payment of the Transaction Price is credited to the bank account of the Company within [3] days of booking the Transaction. Payment on Delivery shall mean a Transaction where the payment for the items is collected from the buyer by the Logistics Partner at the time of delivering the goods. In this case, the Buyer shall only make payment in cash and no other mode of payment will be accepted. However, this facility is not available</p>
<p>with CINEFILMSLANKA (PVT) LTD as all products are created based on order from the Buyers / Customers only.</p>
<p>
  <br>
</p>
<p>Delivery / Delivered means physical delivery of the items to the buyer (for which a Transaction Price has been paid by the buyer or such other mode of payment approved by the Company in writing) by the seller through a reputed courier service / Logistics Partner currently India Post at the address communicated to the buyer on CINEFILMSLANKA (PVT) LTD portal. The mode of shipment is at the discretion of the company.</p>
<p>
  <br>
</p>
<p>In Transit/ Dispatched all mean that the items (for which a Transaction Price has been paid by the buyer or such other mode of payment approved by the Company) have been dispatched by the seller through a reputed courier service / Logistics Partner at the address communicated by the buyer on CINEFILMSLANKA (PVT) LTD portal.</p>
<p>
  <br>
</p>
<p>Dispatch Details means the true, accurate and valid data, information, details or documents as specified by the Company from time to time, which the seller/ Logistics Partner is obligated to provide to the Company as proof that the item has been Dispatched and/or Delivered, as the case maybe.</p>
<p>
  <br>
</p>
<p>Information means and shall include any confidential and/or personally identifiable information or other information provided to the Company or other Users of CINEFILMSLANKA (PVT) LTD at the time of registration, buying or listing process or through any email feature and shall include without limitation your name, email address, billing/shipping address, phone number and banking / financial information.</p>
<p>
  <br>
</p>
<p>Issuing Bank in respect of a buyer, means any bank that has issued a Valid Card (credit/ debit/ cash card) to the buyer or the branch of a bank which maintains a valid Bank Account in the name of buyer; with which the buyer makes payment of the Transaction Price. [Currently, CINEFILMSLANKA (PVT) LTD authorized Payment Gateway Facility supports online bank transfers from the banks that are available while selecting prepay as the payment method. The Company may add or remove or suspend any one or</p>
<p>
  <br>
</p>
<p>more banks directly or through any payment gateway facilitators and such change shall come into effect upon the same being posted on CINEFILMSLANKA (PVT) LTD portal.</p>
<p>
  <br>
</p>
<p>Logistics Partner shall mean reputable logistics and courier company(s) appointed by the Company that will provide various services such as pickup and delivery of items.</p>
<p>
  <br>
</p>
<p>Transaction means every electronically generated valid purchase order placed by the Buyer for purchasing the items listed by the Seller on CINEFILMSLANKA (PVT) LTD portal.</p>
<p>
  <br>
</p>
<p>Transaction Price means the price to be paid for the items to be purchased by the buyer for every Transaction and which price shall include, if applicable, the shipping charges, insurance charges and all other taxes, duties, costs, charges and expenses in respect thereof as charged as per the current Indian Government laws which is the GST.</p>
<p>
  <br>
</p>
<p>Valid Card means any valid credit card/ valid debit card/ valid cash card or any other card of whatsoever nature issued by Visa or MasterCard and/or by any Issuing Bank or any institution designated to issue such cards and lawfully owned by the User of the card at the time of the Transaction as well as at the time of Refund, if any.</p>
<p>
  <br>
</p>
<p>Valid Bank Account shall mean a valid and operational bank account in the name of the User of which the User is the rightful and legal owner having the ability to issue cheques/ demand drafts and make deposits, which in respect of the buyer shall be referred to as the Buyer Bank Account and in respect of the Seller be referred to as the Seller Bank Account. [Both the Buyer Bank Account and Seller Bank Account are required to be with a branch of a nationalized bank as per applicable Indian laws or other banks which are registered with or approved by Reserve Bank of India and such branch and/or account of the Buyer and Seller supports Reserve Bank of India’s electronic / online banking system including, without limitation, National Electronic Funds Transfer (NEFT) and/or Real Time Gross Settlement (RTGS)].</p>
<p>
  <br>
</p>
<p>CINEFILMSLANKA (PVT) LTDauthorized Payment Gateway facility means the automated electronic payment or collection and remittance facility provided by the Company to Buyers and Sellers to facilitate purchase and sale of items as well as making payments there for on CINEFILMSLANKA (PVT) LTD directly through banks or financial institution infrastructure or indirectly through payment gateway facility providers or through any such facility authorized by the Reserve Bank of India to provide enabling support facility for collection and remittance of payment. [Currently, CINEFILMSLANKA (PVT) LTD authorized Payment Gateway Facility supports online bank transfers from the banks that are available while selecting the Prepay mode as the payment method. The Company may add or remove or suspend any one or more banks directly or through any payment gateway facilitators, and such change shall come</p>
<p>
  <br>
</p>
<p>into effect upon the same being posted on CINEFILMSLANKA (PVT) LTD.]. The company has the right to change the payment gateway service as and when required.</p>
<p>
  <br>
</p>
<p>Current Payment modes on CINEFILMSLANKA (PVT) LTD.in through our Payment gateway partner Payhere are mentioned below.</p>
<p>– Credit Card – We support all major local and international credit cards (visa, Amex, Master Card, Diners Discover).</p>
<p>- Visa, Master, Amex, Discover, HelaPay, Diners Club, Genie, Frimi, ezcash, Mcash,Sampath Vishwa, Ipay.</p>
<p>– We are SSL certified.</p>
<p>
  <br>
</p>
<p>Eligibility</p>
<p>CINEFILMSLANKA (PVT) LTD portal or any service provided by CINEFILMSLANKA (PVT) LTD portal may only be used or accessed by such persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are ‘incompetent to contract’ within the meaning of the Indian Contract Act, 1872 including minors, persons of unsound mind, and undercharged insolvents are not eligible to use CINEFILMSLANKA (PVT) LTD portal. A minor is not allowed to access or register as a User or sell or purchase any items on CINEFILMSLANKA (PVT) LTD portal. If you represent and are registering as a business entity, by accepting the User Agreement you represent that such entity has sufficient authority under applicable law to enter into the User Agreement and you are duly authorized by the business entity to accept this User Agreement and you have the authority to bind that business entity to this User Agreement.</p>
<p>
  <br>
</p>
<p>Registration and Communication</p>
<p>By registering on CINEFILMSLANKA (PVT) LTD, you agree to allow us to contact you through any mode of communication (Email/Chat/Telephone call) for any confirmation or service related information for the order placed by you, on the contact details provided by you. Any kind of legal implication arose, due to the incorrect nature of the details provided by you, CINEFILMSLANKA (PVT) LTD will not be held responsible for the same.</p>
<p>
  <br>
</p>
<p>You agree that your sole purpose of registering or using CINEFILMSLANKA (PVT) LTD is to buy unique handmade products including ethnic products or such products as may be specifically notified by the Company on the Website from time to time (that are permitted to be bought and sold under applicable law) and you shall not use CINEFILMSLANKA (PVT) LTD for any other purpose including for selling or buying products other than as mentioned above or products that are not allowed under applicable law to be sold or bought by you in any manner.</p>
<p>You agree to provide true, accurate and complete information while registering or for any other purpose when prompted to do so on CINEFILMSLANKA (PVT) LTD. You are prohibited from misrepresenting your identity and agree not to represent yourself as another User or login/ register using the identity of any other person. You are responsible to maintain and promptly update the information provided while registering or for any other purpose on CINEFILMSLANKA (PVT) LTD to ensure that the information provided by you is true, accurate, current and complete at all times. If you provide any information that is untrue, inaccurate, not current or incomplete or the Company has reasonable grounds to deduce that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this User Agreement, the Company reserves the right to indefinitely suspend or terminate or block your use or access to CINEFILMSLANKA (PVT) LTD in any manner whatsoever.</p>
<p>
  <br>
</p>
<p>Buyer Registration: Other than being a User, there is no separate registration requirement for buyers. CINEFILMSLANKA (PVT) LTD authorized Payment Gateway facility is available to Buyers who hold a Valid Card or Valid Bank Account. It is not mandatory to register to place an order on CINEFILMSLANKA (PVT) LTD portal.</p>
<p>
  <br>
</p>
<p>Electronic Communication: You agree to keep yourself updated with all data, information and communication pertaining to you made available on CINEFILMSLANKA (PVT) LTD. You further agree that your use of CINEFILMSLANKA (PVT) LTD portal or provision of any data or information including any correspondence (by email or otherwise) to or by the Company is through electronic records and you consent to receive communication from the Company via electronic records which will be deemed adequate service of notice/ electronic record.</p>
<p>
  <br>
</p>
<p>Terms of Use</p>
<p>You understand and agree that the Company merely provide hosting services to its Users who access CINEFILMSLANKA (PVT) LTD for purchase and sale of unique Indian products (that are permitted to be bought and sold under applicable law). All items advertised and/or listed on CINEFILMSLANKA (PVT) LTD and the contents therein are advertised and listed by Users and are third party purchasers and/or sellers as the case may be. You also give permission to the Website and the Company to store details and records of your usage of CINEFILMSLANKA (PVT) LTD indefinitely. However, this does not constitute any obligation on the part of the Company or the Website to do so.</p>
<p>
  <br>
</p>
<p>Currently the membership on CINEFILMSLANKA (PVT) LTD is free and the Company does not levy any charges/fees for browsing or buying on CINEFILMSLANKA (PVT) LTD. However, for the purposes of listing any item on CINEFILMSLANKA (PVT) LTD to be sold or availing other services provided by the Company through CINEFILMSLANKA (PVT) LTD such as packing, warehousing, courier etc., the Seller will be charged fees as provided in the Facility Charges Policy incorporated herein by reference. The Company reserves the right to introduce new services or modify the existing services provided on CINEFILMSLANKA (PVT) LTD. Additionally, the Company at its sole discretion may introduce fees for the new services provided or amend/ introduce fees for the existing services, as the case may be. Changes to the User Agreement or any of the rules and policies of the Company shall be posted on CINEFILMSLANKA (PVT) LTD and such changes shall automatically become effective immediately after they are posted on CINEFILMSLANKA (PVT) LTD.</p>
<p>
  <br>
</p>
<p>All fees/ charges shall be quoted in Indian Rupees and shall be payable to CINEFILMSLANKA (PVT) LTD within such time as specified in the invoice. You are responsible for paying all charges/ fees associated with the use of CINEFILMSLANKA (PVT) LTD and shall be liable to pay any and all applicable taxes, charges, cesses etc. which may be levied. In case of any non- payment, the Company reserves the right to issue a warning or temporarily/ indefinitely suspend or terminate your membership with CINEFILMSLANKA (PVT) LTD and disallow access to CINEFILMSLANKA (PVT) LTD. The Company also reserves the right to take any legal action against you in case of any non- payment of charges/fees to the Company.</p>
<p>
  <br>
</p>
<p>If you purchase anything on CINEFILMSLANKA (PVT) LTD, you agree to also comply with the terms and conditions set out in the Policy for Buyers incorporated herein by reference. All our products are handmade and the payment needs to be made in advance and the delivery time lines shall be communicated before the customer / buyer makes the payment. As these are handmade products and are human dependent the company has a right to change delivery time lines subject to the acceptance of the buyer in case there is a delay and is accepted by the buyer and seller in writing.</p>
<p>
  <br>
</p>
<p>You agree that the Company may appoint any third party service provider, including but not restricted to one or more of the Company’s affiliate to provide backend operations and support as instructed by the Company from time to time including but not limited to collection, processing and remittance of the Transaction Price using the existing authorized banking infrastructure to provide enabling support facility for collection and remittance of payment including but not limited to the Logistics Partner. The Company neither originates nor transmits any communication/ information on behalf of any User nor does it modify the contents of any communication transmitted. The Company has no control over third parties and contents generated by the Users on CINEFILMSLANKA (PVT) LTD.</p>
<p>
  <br>
</p>
<p>Any information provided by you to the Company or submitted to CINEFILMSLANKA (PVT) LTD or provide or display to other Users of CINEFILMSLANKA (PVT) LTD in the registration, buying or listing process, in the feedback area or through any e-mail communication is solely your responsibility and the Company merely is a platform where such information is distributed, published, displayed or used by Users. The Company or the Website is not liable for accuracy, appropriateness or legality of such information.</p>
<p>
  <br>
</p>
<p>User Obligations</p>
<p>All contractual terms of the manner and terms &amp; conditions of delivery, payment, insurance etc. between the buyer and the seller shall be independently agreed with the other users of CINEFILMSLANKA (PVT) LTD that you may transact with. You will treat CINEFILMSLANKA (PVT) LTD as a mere passive conduit which is used as a platform by Users to create listings or provide information for the purpose of selling their items so that such information can be discovered and read by other Users of CINEFILMSLANKA (PVT) LTD who may wish to purchase such items from other Users or provide feedback on items they have purchased or sellers who have sold any item to them.</p>
<p>
  <br>
</p>
<p>You agree and undertake not to host, display, upload, modify, publish, transmit, update or share any information or list any information or item that: Belongs to another person and to which you do not have any right to; Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986; Harm minors in any way; Infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen items; Violates any law for the time being in force; Deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; Impersonate another person or use an anonymous proxy; Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancelbots, Easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</p>
<p>
  <br>
</p>
<p>Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation; </p>
<p>Shall not be false, inaccurate or misleading; </p>
<p>Shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force; </p>
<p>May give rise to liability on part of the Website or the Company or cause any hindrance (in whole or in part) with respect to the services of ISPs or other suppliers of the Website or the Company; and </p>
<p>Link directly or indirectly to or include descriptions of items that are (i) prohibited under the User Agreement or any other applicable law for the time being in force including but not limited to the Drugs and Cosmetics Act, 1940, the Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954, the Indian Penal Code, 1860, Information Technology Act 2000 as amended time to time and rules there under or (ii) are at the same time listed for sale on a web site other than CINEFILMSLANKA (PVT) LTD. You shall not promote any website or webpage or link on CINEFILMSLANKA (PVT) LTD.</p>
<p>In case of any violation of the above provisions, the Company has the right to immediately terminate the access or usage rights of the user to CINEFILMSLANKA (PVT) LTD without any notice and any such violating information that is displayed or submitted on CINEFILMSLANKA (PVT) LTD can be removed immediately and completely.</p>
<p>
  <br>
</p>
<p>You shall be responsible for keeping backup versions of the information and data provided by you. You hereby agree that you will not expect CINEFILMSLANKA (PVT) LTD to restore or keep back up of your information and data and not hold the Website or the Company accountable for any loss of data in any circumstances.</p>
<p>
  <br>
</p>
<p>You shall not, either alone or in conjunction with other users, manipulate or attempt to manipulate the prices of any item being sold or purchased on CINEFILMSLANKA (PVT) LTD. You will also refrain from accessing information or databases in an unauthorized manner from CINEFILMSLANKA (PVT) LTD or servers where information or databases are kept.</p>
<p>
  <br>
</p>
<p>You shall not attempt to or circumvent or manipulate any of the obligations conferred on you by this User Agreement. If such attempt is discovered, it will constitute sufficient ground for termination of access to CINEFILMSLANKA (PVT) LTD and also for taking appropriate legal action.</p>
<p>
  <br>
</p>
<p>In case of any transaction or attempted transaction pertaining to any item listed on CINEFILMSLANKA (PVT) LTD which is violating this User Agreement or applicable laws comes to your knowledge, you shall forthwith take all steps to inform the Company of such violation at contactus@CINEFILMSLANKA (PVT) LTD.com.</p>
<p>
  <br>
</p>
<p>If you choose to provide feedback on CINEFILMSLANKA (PVT) LTD which is visible to other users, you shall exercise due care while making comments and not make any comments that are not factual in nature and shall not post defamatory or illegal or offensive/ obscene contents.</p>
<p>
  <br>
</p>
<p>You undertake not to disclose or distribute any other User’s Information to a third party, or use the Information for any unauthorized purpose including for the purposes of marketing unless you have obtained the User’s express consent to do so.</p>
<p>You shall not place any advertisements on the Website in any manner. Further, you shall not use the Website to promote your own or any other persons business or interests on the Website except for providing description on a listing for a specific item, unless permitted by the Company in writing.</p>
<p>
  <br>
</p>
<p>You shall not attempt to ‘double dip’ during the course of a dispute by receiving or attempting to receive funds from the Company and/or its service providers and/or the buyer or seller as the case maybe.</p>
<p>
  <br>
</p>
<p>Disclaimers</p>
<p>CINEFILMSLANKA (PVT) LTD is only a platform where users may meet and interact with one another for their transactions. The Website or the Company is not and cannot be a party to or control in any manner any transaction between two users of CINEFILMSLANKA (PVT) LTD.</p>
<p>All commercial / contractual terms are offered by and agreed to between buyers and sellers alone as perprincipal to principal bipartite contractual obligations. The commercial / contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to items listed for sale. The Company does not have any control and neither does it determine or advise or in any way involves itself in the offering or acceptance of such commercial / contractual terms between buyers and sellers. Further, you understand that a listing may end if another User buys the item, or the User who made the listing chooses to end the same or if the listing expires after a stipulated period of time.</p>
<p>
  <br>
</p>
<p>The Company is neither involved in the buying and selling of items on the Website nor liable or responsible for any non- performance or breach of any contract entered into between the Users (i.e. buyer and seller) including but not limited to non-delivery or non-receipt, non-payment, damage, breach of representations and warranties provided by the seller or any fraud as regards the items listed on CINEFILMSLANKA (PVT) LTD. The Users acknowledge that the Company will not be liable for any damages, interests or claims etc. resulting from not processing or any delay in processing a Transaction/</p>
<p>
  <br>
</p>
<p>Transaction Price which is beyond the control of the Company. The Company shall not and is not required to mediate or resolve any dispute or disagreement between users. The Company does not make any representation or warranty as to the attributes (such as quality, worth, marketability, merchantability, usefulness) of the items proposed to be sold or offered to be sold or purchased on CINEFILMSLANKA (PVT) LTD. In particular, the Company does not implicitly or explicitly support or endorse the sale or purchase of any items on the Website. The Company shall not be liable for any errors or omissions, whether on behalf of itself or third parties.</p>
<p>
  <br>
</p>
<p>The Company does not make any representation or warranty as to the attributes (such as legal title, creditworthiness, identity etc.) of any of its users. You are advised use your best judgment and independently verify the bona fides of any particular User that you choose to deal with on CINEFILMSLANKA (PVT) LTD.</p>
<p>
  <br>
</p>
<p>CINEFILMSLANKA (PVT) LTD is only a venue through which Users can reach a larger base to buy and sell unique Indian Hand Made / Hand Crafted products. The Company is only providing a platform in form of the Website for communication and a hosting service for information and it is agreed that the contract for sale of any of the items shall be a strictly bipartite contract between the seller and the buyer. At no time shall any right, title or interest over the items vest with the Company nor shall the Company have any obligations or liabilities in respect of such contract. The Company is not responsible for unsatisfactory or delayed performance of sellers or damages or delays as a result of items being out of stock, back ordered or otherwise unavailable. All items offered by sellers are only for a restricted time and only for the available supply as offered by sellers.</p>
<p>
  <br>
</p>
<p>The Company and its suppliers, affiliates and service providers make available CINEFILMSLANKA (PVT) LTD and services including the CINEFILMSLANKA (PVT) LTD Logistics, CINEFILMSLANKA (PVT) LTD authorized Payment Gateway facility for electronic payment on an “as is” basis and without any warranty or condition, express, implied or statutory and specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. The Company specifically disclaims any such warranty. You expressly agree that the use of CINEFILMSLANKA (PVT) LTD and CINEFILMSLANKA (PVT) LTD authorized payment gateway electronic payment facility is at your own risk.</p>
<p>You release and indemnify the Company and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the users of CINEFILMSLANKA (PVT) LTD and specifically waive any claims that you may have in this behalf under any applicable law. The Company cannot control the information provided by other Users, which is made available on the Website notwithstanding the Company’s reasonable efforts in that behalf. You may find other User’s information to be offensive, harmful, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website. Please note that there may be risks in dealing with foreign nationals, underage persons or people acting under false pretence.</p>
<p>
  <br>
</p>
<p>Limited liability of the Company</p>
<p>In no event shall the Company or its suppliers, affiliates and service providers be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising (in any manner whatsoever, including but not limited to negligence) out of or in connection with CINEFILMSLANKA (PVT) LTD, CINEFILMSLANKA (PVT) LTD authorized payment gateway facility, services provided by the Logistics Partner or any other services or this User Agreement.</p>
<p>
  <br>
</p>
<p>The Company liability in any circumstance is limited to the amount of charges/ fees, if any, paid by you to the Company. The Company, its associates, affiliates and service providers and technology partners make no representations or warranties about the accuracy, reliability, completeness, and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of CINEFILMSLANKA (PVT) LTD or that the operation of CINEFILMSLANKA (PVT) LTD or the Logistics Partner or CINEFILMSLANKA (PVT) LTD authorized payment gateway facility will be error free and/or uninterrupted. The Company provides no guarantee to its Users in respect of the products sold on the Website. Consequently, the Company assumes no liability whatsoever for any monetary or other damage suffered by you on account of:</p>
<p>
  <br>
</p>
<p>The delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Website or CINEFILMSLANKA (PVT) LTD authorized payment gateway facility. Any delay, failure, interruption or errors in the operation of CINEFILMSLANKA (PVT) LTD or the Logistics Partner or CINEFILMSLANKA (PVT) LTD authorized payment gateway facility.</p>
<p>Indemnity</p>
<p>You shall indemnify and hold harmless the Company and the Company’s parent, subsidiaries, affiliates, third-parties and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of the User Agreement including the rules and policies incorporated herein by reference, or (ii) your violation of any law, rules or regulations or the rights of a third party.</p>
<p>Payment</p>
<p>
  <br>
</p>
<p>Payments for the items on CINEFILMSLANKA (PVT) LTD, at the option of the relevant seller, can be made by way of (i) Payment on Billing which can be made through the CINEFILMSLANKA (PVT) LTD authorized payment gateway Facility or by depositing cash, cheque, demand draft in the bank account of the Company; or (ii) Payment on Delivery wherein payment shall be made only by cash on delivery, or such other method of payment as may be permitted by the Company on CINEFILMSLANKA (PVT) LTD in its sole discretion.</p>
<p>
  <br>
</p>
<p>For the purposes of buying and/or selling any item listed on CINEFILMSLANKA (PVT) LTD, you agree and undertake not to make payments in any manner other than as provided, without the prior consent of the Company.</p>
<p>
  <br>
</p>
<p>You acknowledge and accept that you have specifically authorized the Company to collect, process, facilitate and remit payments and/ or the Transaction Price by any of the prescribed methods of payment through Payment on Billing or Payment on Delivery to and from other Users in respect of Transactions.</p>
<p>
  <br>
</p>
<p>In order to enable Users to carry out transactions on CINEFILMSLANKA (PVT) LTD, the Company will in addition to other methods of payment provide an electronic payment facility i.e. CINEFILMSLANKA (PVT) LTD authorized payment gateway facility by E-billing Solutions Private Limited on the Website. The CINEFILMSLANKA (PVT) LTD authorized payment gateway facility enables automated collection and remittance services using the facilities of various Indian banks, financial institutions, credit/ debit/ cash card brands, various third party service providers and/or payment card industry issuers and through such other infrastructure and facilities as may be authorized by the Reserve Bank of India for collection, refund and remittance, as the case may be. The CINEFILMSLANKA (PVT) LTD authorized payment gateway facility shall be availed in accordance with the terms of this User Agreement and the rules and policies prescribed hereunder.</p>
<p>
  <br>
</p>
<p>The Company shall make reasonable efforts to ensure that requests for electronic debits and credits involving Issuing Bank are informed to the Nodal Bank (defined below) in a timely manner. However, a number of factors that are outside of the Company’s control (including without limitation actions of Issuing Bank, Nodal Bank and the bank or credit / debit/ cash card and/or banks or financial institution infrastructure or indirectly through payment gateway facility providers or through any such facility authorized by the Reserve Bank of India to provide enabling support facility for collection and remittance of payment where the Transaction Price is remitted and/or refunded) may delay the time within which the Transaction Price are collected/ remitted by the Company through the CINEFILMSLANKA (PVT) LTD authorized payment gateway facility. The Company neither makes any representations nor makes any warranties regarding the amount of time needed to complete processing, including delays in the banking system and nor shall the Company be liable for any actual or consequential damages arising from any claim of delay.</p>
<p>
  <br>
</p>
<p>Any claim for refund of any payment made to the Company, for any reason whatsoever, shall be to the account of the Seller and the Company shall not be responsible for the same including but not limited to service charges or any other fees/ charges.</p>
<p>
  <br>
</p>
<p>You agree and accept that the Company is neither acting as trustee nor acting in a fiduciary capacity with respect to the Transaction or the Transaction Price, by providing the CINEFILMSLANKA (PVT) LTD authorized payment gateway facility or any other method of payment to its Users.</p>
<p>
  <br>
</p>
<p>Consent and Privacy Policy</p>
<p>By using CINEFILMSLANKA (PVT) LTD and/or by providing your information, you consent to the collection and use of such information disclosed by you on CINEFILMSLANKA (PVT) LTD on CINEFILMSLANKA (PVT) LTD authorized payment gateway facility, by the Company. The personal information / data including but</p>
<p>not limited to the Information provided by the You to CINEFILMSLANKA (PVT) LTD/ CINEFILMSLANKA (PVT) LTD authorized payment gateway facility during the course of a Transaction shall be treated as strictly confidential and retained in accordance with the Privacy Policy which is incorporated herein by reference and applicable laws and regulations including but not limited to Information Technology Act, 2000 and rules there under. The Company does not sell or rent or otherwise disclose your personal information to third parties for their marketing purposes without your explicit consent and the Company only uses your information in the manner described in the Privacy Policy. If you do not agree to your Information being transferred or used in this way, please do not use CINEFILMSLANKA (PVT) LTD. The Company views the protection of user’s privacy as a very important community principle. The Company clearly understands that you and the personal information provided by you is one of the most important assets to the Company. The Company stores and processes the information provided by you in computers located in India that are protected by physical as well as reasonable technological security measures and procedures in compliance with the provisions of the Information Technology Act, 2000 and rules made there under.</p>
<p>
  <br>
</p>
<p>BREACH</p>
<p>Without limiting other remedies that the Company may pursue, the Company may at its sole discretion take such action as it deems fit including but not limited to cancellation of the Transaction or payments made, limit your activity, immediately remove your information or listings, or end your listing, warn other Users of your actions, forthwith temporarily/indefinitely suspend or terminate or block your membership, and/or refuse to provide you with access to CINEFILMSLANKA (PVT) LTD or initiate any legal action it may deem fit, particularly in the event:</p>
<p>
  <br>
</p>
<p>You breach any of the provisions of this User Agreement including any of the rules and policies, documents, terms and conditions made there under which are incorporated therein by reference;</p>
<p>Any misuse of the CINEFILMSLANKA (PVT) LTD authorized payment gateway facility</p>
<p>The Company is unable to verify or authenticate any information provided by you;</p>
<p>The Company believes that your actions may cause legal liability to the Company, other Users or yourself. No actions, omissions or decisions taken by the Company shall waive any rights or claims that the Company may have against the User. No actions, omissions or decisions taken by the Company shall waive any rights or claims that the Company may have against the User.</p>
<p>Any User that may have been suspended or blocked may not register or attempt to register with CINEFILMSLANKA (PVT) LTD or use CINEFILMSLANKA (PVT) LTD in any manner whatsoever until such time that such User is reinstated by the Company. Notwithstanding the above, if you breach the User Agreement or the rules and policies and other documents incorporated therein by reference, the Company reserves the right to recover any amounts due and owed by you to the Company and to take strict legal action including but not limited to referral to the appropriate police or other authorities for initiating criminal or other proceedings against me.</p>
<p>
  <br>
</p>
<p>Grievance Redressal Mechanism</p>
<p>In case of any grievance, objection or complaint on your part with respect to the Website, other Users, CINEFILMSLANKA (PVT) LTD authorized payment gateway facility or the Company, including any complaints or enquiry about suspension, termination or blocking of your membership or right to use CINEFILMSLANKA (PVT) LTD, you should promptly raise such grievance or complaint with the designated Grievance Officer at disputes@CINEFILMSLANKA (PVT) LTD.com and provide him with all necessary information and/or documents to enable the Company/ Grievance Officer to resolve the issue.</p>
<p>
  <br>
</p>
<p>The name and contact details of the Grievance Officer is published on CINEFILMSLANKA (PVT) LTD as required under the provisions of the Information Technology Act, 2000 and the rules made there under.</p>
<p>
  <br>
</p>
<p>General</p>
<p>None of the provisions of this User Agreement shall be deemed to constitute a partnership or agency between you and the Company and you shall have no authority to bind the Company in any manner whatsoever.</p>
<p>
  <br>
</p>
<p>Except as explicitly stated otherwise, any notices directed to the Company shall be given by email to customercare@CINEFILMSLANKA (PVT) LTD.com and any notices to you by the Company shall be provided to the email address provided by you during the registration process. Notice shall be deemed given 72 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you notice by registered mail, postage prepaid and return receipt requested, to the address provided to us during the registration process. In such case, notice shall be deemed given 3 days after the date of mailing.</p>
<p>
  <br>
</p>
<p>If any clause of this User Agreement or the application thereof to any User or circumstance shall be deemed invalid, void or for any reason unenforceable to any extent, the remainder of this User Agreement and the application of such unenforceable provision to Users or circumstances other than those as to which it is held invalid or unenforceable shall not be affected thereby, and each provision of this User Agreement shall be valid and enforceable to the fullest extent permitted by law.</p>
<p>
  <br>
</p>
<p>This User Agreement together with the rules and policies incorporated herein by reference constitutes the entire understanding and agreement between You and the Company with respect to the subject matter herein.</p>
<p>
  <br>
</p>
<p>The Company at its sole discretion shall be entitled to assign or transfer its rights and obligations under this User Agreement hereunder to any other person without your prior consent provided that the Company assigns this User Agreement on the same terms or such terms that are no less favorable to you.</p>
<p>
  <br>
</p>
<p>All remedies of the Company under this User Agreement whether provided herein or conferred by statute, civil law, common law, custom or trade usage, are cumulative and not alternative and may be enforced successively or concurrently.</p>
<p>
  <br>
</p>
<p>ARBITRATION</p>
<p>If any dispute arises between you and the Company during your use of CINEFILMSLANKA (PVT) LTD or the CINEFILMSLANKA (PVT) LTD authorized payment gateway facility or CINEFILMSLANKA (PVT) LTD Services or any service incidental to the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement and/or CINEFILMSLANKA (PVT) LTD authorized payment gateway Agreement, or the rules, policies and documents incorporated therein by reference, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by the Company whose decision shall be final. The place of arbitration shall be Hyderabad, Telangana State, India. The Arbitration &amp; Conciliation Act, 1996, shall govern the arbitration proceedings. The arbitration proceedings shall be in the English language.</p>
<p>
  <br>
</p>
<!--p>GOVERNING LAW</p>
<p>This User Agreement and all rules, policies and documents incorporated by reference shall be governed and construed in accordance with the laws of India and the Courts in Hyderabad, Telangana State shall have exclusive jurisdiction. This document is an electronic record in terms of Information Technology Act, 2000 and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p-->
</div>
<?php include "footer.php"; ?>